### ISSUE TITLE
About the data preparation.

### ISSUE THREAD

**Issue by bowfan94** [farquasar1/ConvLSTM#4]
Hi, thanks for the code.
I'm now trying to run the lstm_train_fcn.py  script and I have some questions:
1. I have 2 video sequence named as  train.mp4 and train_label.mp4, but I don't know which folder should I put these two videos?
2. I got an error  `FileNotFoundError: [Errno 2] No such file or directory: 'splits.txt'`. How should I prepare this 'splits.txt'?
I'd be really appreciated if you can provide some help.

**Comment by 123liluky** [comment]
@farquasar1 @percyfan Have you figured out data preparation steps? I am confused about it too.

**Comment by nohaghatwary** [comment]
@percyfan @farquasar1  I am confused about the data preparation to create a split file,, anyone figured it out???
